// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: summation.proto

package summation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Summation request message
type SummationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *SummationRequest) Reset() {
	*x = SummationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_summation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummationRequest) ProtoMessage() {}

func (x *SummationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummationRequest.ProtoReflect.Descriptor instead.
func (*SummationRequest) Descriptor() ([]byte, []int) {
	return file_summation_proto_rawDescGZIP(), []int{0}
}

func (x *SummationRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SummationRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

// Summation response message
type SummationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SummationResponse) Reset() {
	*x = SummationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_summation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummationResponse) ProtoMessage() {}

func (x *SummationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_summation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummationResponse.ProtoReflect.Descriptor instead.
func (*SummationResponse) Descriptor() ([]byte, []int) {
	return file_summation_proto_rawDescGZIP(), []int{1}
}

func (x *SummationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_summation_proto protoreflect.FileDescriptor

var file_summation_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x10,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x12, 0x0c,
	0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x62, 0x22, 0x2b, 0x0a, 0x11,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x5d, 0x0a, 0x10, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a,
	0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x12, 0x1b, 0x2e,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_summation_proto_rawDescOnce sync.Once
	file_summation_proto_rawDescData = file_summation_proto_rawDesc
)

func file_summation_proto_rawDescGZIP() []byte {
	file_summation_proto_rawDescOnce.Do(func() {
		file_summation_proto_rawDescData = protoimpl.X.CompressGZIP(file_summation_proto_rawDescData)
	})
	return file_summation_proto_rawDescData
}

var file_summation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_summation_proto_goTypes = []interface{}{
	(*SummationRequest)(nil),  // 0: summation.SummationRequest
	(*SummationResponse)(nil), // 1: summation.SummationResponse
}
var file_summation_proto_depIdxs = []int32{
	0, // 0: summation.SummationService.CalculateSum:input_type -> summation.SummationRequest
	1, // 1: summation.SummationService.CalculateSum:output_type -> summation.SummationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_summation_proto_init() }
func file_summation_proto_init() {
	if File_summation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_summation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_summation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_summation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summation_proto_goTypes,
		DependencyIndexes: file_summation_proto_depIdxs,
		MessageInfos:      file_summation_proto_msgTypes,
	}.Build()
	File_summation_proto = out.File
	file_summation_proto_rawDesc = nil
	file_summation_proto_goTypes = nil
	file_summation_proto_depIdxs = nil
}
